# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 21:10
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'required': 'Please enter your name/handle'}, help_text='Give us your name, handle, or alternate identifying mark', max_length=25, verbose_name='Name/Handle')),
                ('email_address', models.EmailField(error_messages={'required': 'Please enter a valid e-mail address'}, help_text='Give us an e-mail address we can use to get in touch with you', max_length=254, verbose_name='E-Mail')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Give us a phone number to reach you at', max_length=128, verbose_name='Phone Number')),
                ('show_name', models.CharField(error_messages={'required': 'Your show must have a name.  You can change it later'}, help_text='A short, catchy title for your show', max_length=45, verbose_name='Show Name')),
                ('show_type', models.IntegerField(choices=[(1, b'Talk'), (2, b'Music'), (3, b'Round Table'), (4, b'Interviews'), (5, b'Free Form')], help_text='What type of show do you want to air', verbose_name='Show Type')),
                ('show_description', models.TextField(error_messages={'required': 'You must submit a description'}, help_text='Briefly describe the format and content of your show', verbose_name='Description')),
                ('primary_preferred_day', models.CharField(choices=[(b'NONE', b'No Preference'), (b'FRIDAY', b'Friday'), (b'SATURDAY', b'Saturday'), (b'SUNDAY', b'Sunday')], error_messages={'required': 'Please choose a preferred day and time'}, help_text='Which day would you prefer your show on', max_length=8, verbose_name='Preferred Day')),
                ('primary_preferred_time', models.CharField(choices=[(b'NONE', b'No Preference'), (b'EARLY MORNING', b'Early Morning (3am-6am)'), (b'MORNING', b'Morning (7am-9am)'), (b'MIDDAY', b'Midday (10am-12pm)'), (b'AFTERNOON', b'Afternoon (1pm - 4pm)'), (b'EVENING', b'Evening (5pm - 9pm)'), (b'LATE NIGHT', b'Late Night (10pm - 2am)')], error_messages={'required': 'Please choose a preferred day and time'}, help_text='What time of day would you prefer', max_length=15, verbose_name='Preferred Time')),
                ('backup_preferred_day', models.CharField(blank=True, choices=[(b'NONE', b'No Preference'), (b'FRIDAY', b'Friday'), (b'SATURDAY', b'Saturday'), (b'SUNDAY', b'Sunday')], help_text='Which day would you prefer your show on', max_length=8, verbose_name='2nd Preferred Day')),
                ('backup_preferred_time', models.CharField(blank=True, choices=[(b'NONE', b'No Preference'), (b'EARLY MORNING', b'Early Morning (3am-6am)'), (b'MORNING', b'Morning (7am-9am)'), (b'MIDDAY', b'Midday (10am-12pm)'), (b'AFTERNOON', b'Afternoon (1pm - 4pm)'), (b'EVENING', b'Evening (5pm - 9pm)'), (b'LATE NIGHT', b'Late Night (10pm - 2am)')], help_text='What time of day would you prefer', max_length=15, verbose_name='2nd Preferred Time')),
                ('contact_via_sms', models.BooleanField(default=False, verbose_name='Contact me about my show via SMS')),
                ('volunteer_interest', models.BooleanField(default=False, verbose_name="I'm interested in volunteering to help")),
            ],
        ),
    ]
